# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f0e684432ae9386dc47730d657538244a68963072fb086327d88d99107856b6315509e016a86231d8fca87a29c38a983852c206eadd907e7aa89d145d88f792

test:
  secret_key_base: 804f404f4319654c3620dec48f38bed9b89b8d308fdac6c44c0706e5abc3be8ac6d378405e3be6fdf4fb91fd2b0e97897a28cc51894d4879da67514483d9f5d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
